backend:
  name: github
  branch: main
  repo: threenine/blog
publish_mode: editorial_workflow
site_url: https://threenine.blog
logo_url: https://threenine.co.uk/images/threenine_tag.png
display_url: https://threenine.blog
show_preview_links: true
media_library:
  name: cloudinary
  config:
    cloud_name: threenine-co-uk
    api_key: 896994212468486
media_folder: "public/images"
public_folder: "/images"
collections:
    - name: "posts"
      identifier_field: title
      label: "Posts"
      folder: "content/posts"
      format: 'frontmatter'
      create: true
      slug: "{{dirname}}/{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string", required: true }
          - {label: "Subtitle", name: "subtitle", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "string", required: true}
          - {label: "Summary" , name: "summary", widget: "text" }
          - label: "Feature Image"
            name: "featureImage"
            widget: "object"
            fields:
              [
               { label: "Url", name: "url", widget: "image" },
               { label: "Title", name: "title", widget: "string" },
              ]
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              [
                { label: "Name", name: "name", widget: "string" },
                { label: "ImageUrl", name: "Image", widget: "image" },
                { label: "Role", name: "role", widget: "string" },
                { label: "GitHub", name: "github", widget: "string" },
              ]
          - {label: "Publish Date", name: "publishDate", widget: "string" }
          - {label: "Publish Date time", name: "publishDateTime", widget: "string" }
          - {label: "Body", name: "body", widget: "markdown" }
